#!/bin/bash
# following steps as defined here: https://jwst-pipeline.readthedocs.io/en/latest/jwst/pipeline/calwebb_detector1.html#calwebb-detector1
conda activate JWST
export CRDS_PATH=$HOME/crds_cache/jwst_pub
export CRDS_SERVER_URL=https://jwst-crds-pub.stsci.edu
echo ""
echo "****running group scale****"
echo ""
strun group_scale $1_uncal.fits
echo ""
echo "****running dq_init****"
echo ""
strun dq_init $1_groupscalestep.fits
echo ""
echo "****running saturation****"
echo ""
strun saturation $1_dqinitstep.fits
echo ""
echo "****running superbias****"
echo ""
strun superbias $1_saturationstep.fits
echo ""
echo "****running refpix****"
echo ""
strun refpix $1_superbiasstep.fits --odd_even_columns True
echo ""
echo "****running linearity****"
echo ""
strun linearity $1_refpixstep.fits
echo ""
echo "****running dark_current****"
echo ""
strun dark_current $1_linearitystep.fits
echo ""
echo "****running 1overf_subtraction.py****"
echo ""
python $HOME/python/reduction_utils/JWST_utils/1overf_subtraction.py $1_darkcurrentstep.fits --extraction_input /Users/james/JWSTdata/GJ486/MAST_2023-01-30T0503/JWST/transit1/jw01981011001_04102_00001-seg001_nrs1/finding_the_trace/extraction_input_v2.dat --trace_location /Users/james/JWSTdata/GJ486/MAST_2023-01-30T0503/JWST/transit1/jw01981011001_04102_00001-seg001_nrs1/finding_the_trace/pickled_objects/x_positions_1.pickle
echo ""
echo "****running ramp_fit****"
echo ""
strun ramp_fit $1_darkcurrentstep.fits --suppress_one_group True
echo ""
echo "****running gain_scale****"
echo ""
strun gain_scale $1_1_rampfitstep.fits
echo ""
echo "****running assign_wcs****"
echo ""
strun assign_wcs $1_1_gainscalestep.fits
echo ""
echo "****running extract_2d****"
echo ""
strun extract_2d $1_1_assignwcsstep.fits
conda deactivate
