#!/bin/bash
# following steps as defined here: https://jwst-pipeline.readthedocs.io/en/latest/jwst/pipeline/calwebb_detector1.html#calwebb-detector1
#conda activate JWST
export CRDS_PATH=$HOME/crds_cache/jwst_pub
export CRDS_SERVER_URL=https://jwst-crds-pub.stsci.edu
echo ""
echo "****running group scale****"
echo ""
strun group_scale $1_uncal.fits
echo ""
echo "****running dq_init****"
echo ""
strun dq_init $1_groupscalestep.fits --override_mask $HOME/crds_cache/jwst_pub/references/jwst/nircam/jwst_nircam_mask_0063.fits
echo ""
echo "****running saturation****"
echo ""
strun saturation $1_dqinitstep.fits --override_saturation $HOME/crds_cache/jwst_pub/references/jwst/nircam/jwst_nircam_saturation_0097.fits
echo ""
echo "****running superbias****"
echo ""
strun superbias $1_saturationstep.fits --override_superbias $HOME/crds_cache/jwst_pub/references/jwst/nircam/jwst_nircam_superbias_0142.fits
echo ""
echo "****running refpix****"
echo ""
strun refpix $1_superbiasstep.fits --odd_even_columns True
echo ""
echo "****running linearity****"
echo ""
strun linearity $1_refpixstep.fits --override_linearity $HOME/crds_cache/jwst_pub/references/jwst/nircam/jwst_nircam_linearity_0052.fits
echo ""
echo "****running dark_current****"
echo ""
strun dark_current $1_linearitystep.fits --override_dark $HOME/crds_cache/jwst_pub/references/jwst/nircam/jwst_nircam_dark_0363.fits
echo ""
echo "****running 1overf_subtraction.py****"
echo ""
python $HOME/python/Tiberius/src/reduction_utils/JWST_utils/1overf_subtraction.py $1_darkcurrentstep.fits --extraction_input /Users/james/JWSTdata/GJ341b/MAST_2023-03-04T0414/JWST/jw01981032001_04103_00001-seg001_nrcalong/finding_the_trace/extraction_input_v2.dat --trace_location /Users/james/JWSTdata/GJ341b/MAST_2023-03-04T0414/JWST/jw01981032001_04103_00001-seg001_nrcalong/finding_the_trace/pickled_objects/x_positions_1.pickle
echo ""
echo "****running ramp_fit****"
echo ""
strun ramp_fit $1_darkcurrentstep.fits --suppress_one_group True --override_readnoise $HOME/crds_cache/jwst_pub/references/jwst/nircam/jwst_nircam_readnoise_0199.fits --override_gain /Users/james/crds_cache/jwst_pub/references/jwst/nircam/jwst_nircam_gain_0097.fits
echo ""
echo "****running gain_scale****"
echo ""
strun gain_scale $1_1_rampfitstep.fits --override_gain $HOME/crds_cache/jwst_pub/references/jwst/nircam/jwst_nircam_gain_0097.fits
echo ""
echo "****running assign_wcs****"
echo ""
strun assign_wcs $1_1_gainscalestep.fits
echo ""
echo "****running extract_2d****"
echo ""
strun extract_2d $1_1_assignwcsstep.fits
echo ""
echo "****cleaning directory****"
rm $1_0_rampfitstep.fits
rm $1_1_rampfitstep.fits
rm $1_darkcurrentstep.fits
rm $1_dqinitstep.fits
rm $1_groupscalestep.fits
rm $1_linearitystep.fits
rm $1_refpixstep.fits
rm $1_saturationstep.fits
rm $1_superbiasstep.fits
#conda deactivate
